name: Docker Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ThriveX-Admin
        uses: actions/checkout@v3
        with:
          repository: LiuYuYang01/ThriveX-Admin
          ref: main
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thrivex-admin:latest
          build-args: |
            VITE_VERSION=${{ secrets.VITE_VERSION }}
            VITE_PROJECT_API=${{ secrets.VITE_PROJECT_API }}
            VITE_BAIDU_TONGJI_SITE_ID=${{ secrets.VITE_BAIDU_TONGJI_SITE_ID }}
            VITE_BAIDU_TONGJI_ACCESS_TOKEN=${{ secrets.VITE_BAIDU_TONGJI_ACCESS_TOKEN }}
            VITE_AI_APIPASSWORD=${{ secrets.VITE_AI_APIPASSWORD }}
            VITE_AI_MODEL=${{ secrets.VITE_AI_MODEL }}
            VITE_GAODE_WEB_API=${{ secrets.VITE_GAODE_WEB_API }} 